### ISSUE TITLE
Does the dataset require preprocessing？

### ISSUE THREAD

**Issue by Mariosz2** [lhaof/CellSeg#3]
Hi, 
I have two questions about datasets.
1. Do the masks (or labels) files in the dataset need to be preprocessed?
In the public dataset you mentioned, some of the mask files corresponding to the images have different mask values for each cell. In your training model, do I need to first process these mask files into a format similar to the following :
```
three-class map, values: 0,1,2
0: background
1: interior
2: boundary
```
2. Does the image in the dataset need to be preprocessed?
The formats and types of images in these datasets are quite different. Before passing your model, do I need to pre-process and convert them into PNG format (such as pre-processing through pre_process_3class.py in the official baseline)?

I would greatly appreciate it if I could receive help.

**Comment by Lewislou** [comment]
Hi,

The images need to be preprocessed just like the pre-processing codes used in pre_process_3class.py, for example, convert the single-channel images into RGB images. However, the label maps in our method do not need to be processed into interior/boundary, the label maps are instance maps that are stored in the .tif images as the original competition datasets.

Hope this answer could help~

**Comment by Mariosz2** [comment]
Thanks for your reply.
I want to ask another question about the details of the training process of the classifier ResNet18. Based on your paper, because low-level features including the characteristics of cell masks are used for classification, the input of `unsup-classification.py` should be the unprocessed original image, while the input of ResNet18 training(in `train_classification.py`) is the normalized preprocessed RGB image. Is it right?

**Comment by Lewislou** [comment]
Yes, that's right.

**Comment by Mariosz2** [comment]
Thank you so much!
