### ISSUE TITLE
No module named 'classifiers'

### ISSUE THREAD

**Issue by jingnian-yxq** [lhaof/CellSeg#4]
When I run predict.py, it received an ERROR: No module named 'classifiers'. I found that this module is imported for utilizing resnet18. I try to find resnet18 from other websites but I'm afraid it may not be suitable for this code. 
Could you please share the 'classifiers' module?

**Comment by Lewislou** [comment]
Hi, thanks for using our codes. We have added the classifier.py file and updated the latest codes. Feel free to ask any more questions on inference or training.

**Comment by jingnian-yxq** [comment]
Thank you!

And sorry to bother you with another problem: in ./models/__init__.py, No module named 'models.unetr2d', and no module 'models.swin_unetr' as well. 

I found unetr2d.py in the [NeurIPS-CellSeg-Baseline], while swin_unetr can not be found. Since I'm just trying the inference stage, I simply commented them out. But I notice when training they are necessary. Could you please have a look at it?

PS. After the two imports are commented out, predict.py can run successfully, however the results (label.tif and mask.tif) look like are all fully black. I'm still trying to figure it out.

**Comment by lhaof** [comment]
> Thank you!
> 
> And sorry to bother you with another problem: in ./models/**init**.py, No module named 'models.unetr2d', and no module 'models.swin_unetr' as well.
> 
> I found unetr2d.py in the [NeurIPS-CellSeg-Baseline], while swin_unetr can not be found. Since I'm just trying the inference stage, I simply commented them out. But I notice when training they are necessary. Could you please have a look at it?
> 
> PS. After the two imports are commented out, predict.py can run successfully, however the results (label.tif and mask.tif) look like are all fully black. I'm still trying to figure it out.

jingnian, please @Lewislou 

I suggest you to directly send your questions to weilou@link.cuhk.edu.cn and lhaof@foxmail.com

**Comment by Lewislou** [comment]
> Thank you!
> 
> And sorry to bother you with another problem: in ./models/**init**.py, No module named 'models.unetr2d', and no module 'models.swin_unetr' as well.
> 
> I found unetr2d.py in the [NeurIPS-CellSeg-Baseline], while swin_unetr can not be found. Since I'm just trying the inference stage, I simply commented them out. But I notice when training they are necessary. Could you please have a look at it?
> 
> PS. After the two imports are commented out, predict.py can run successfully, however the results (label.tif and mask.tif) look like are all fully black. I'm still trying to figure it out.

For the "import models.unetr2d" issue. These two models are unrelated to our method, so you can simply comment on them either in inference or training.
The predictions are visually black because they are stored in .jiff with int16 format. If you want to visualize the results, you can use the overlay.py that we provide for better visualization. The usage is in predict_unet_convnext.py.
![image](https://github.com/lhaof/CellSeg/assets/23080469/af678bef-6b4e-4f2c-b293-94b85a7054a2)

**Comment by jingnian-yxq** [comment]
Thank you for your responses. It works! And I am going to try on my own data then. 
Best wishes for your future research endeavors!
